# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.openshift.tag="httpd, php" \
      io.openshift.expose-services="8080:http" \
      io.k8s.display-name="Name" \
      io.k8s.desription="test" 



RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN sed -i "s/#serverName www.example.com:80/serverName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd 


EXPOSE 8080

USER 1001
